version: '3.1'
services:
  my-wordpress:
    image: ssl_wordpress:1.0
    container_name: my-wp-container
    restart: always
    volumes:
      - ./www:/var/www/html
    ports:
      - 80:80
      - 443:443
    links:
      - mysqlserver:mysql
    depends_on:
      - mysqlserver

  mysqlserver:
    image: mariadb:latest
    container_name: my-db-container
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      # MYSQL_DATABASE: wordpress
      # MYSQL_USER: something_special
      # MYSQL_PASSWORD: something_secret
